package vistas;

import acceso.ClienteDAO;
import acceso.DetalleVentaDAO;
import acceso.ProductoDAO;
import acceso.VentaDAO;
import entidades.DetalleVenta;
import entidades.Producto;
import entidades.Venta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Johnny
 */
public class Modificar_Venta extends javax.swing.JDialog {

    ProductoDAO prodao = new ProductoDAO();
    ClienteDAO clidao = new ClienteDAO();
    VentaDAO vedao = new VentaDAO();
    DetalleVentaDAO detadao = new DetalleVentaDAO();
    List<Producto> listaproductos = new ArrayList();

    /**
     * Creates new form Modificar_Venta
     */
    public Modificar_Venta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbIdDetalle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbIdVenta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboCantidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actualizar Detalle de Venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("ID Detalle Venta:");

        lbIdDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIdDetalle.setForeground(new java.awt.Color(0, 0, 0));
        lbIdDetalle.setText("o");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("ID Venta:");

        lbIdVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIdVenta.setForeground(new java.awt.Color(0, 0, 0));
        lbIdVenta.setText("o");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Producto:");

        comboProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboProductos.setForeground(new java.awt.Color(0, 0, 0));
        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Cantidad:");

        comboCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboCantidad.setForeground(new java.awt.Color(0, 0, 0));
        comboCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCantidadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Precio Total:");

        lbPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(255, 0, 0));
        lbPrecio.setText("p");

        btnActualizar.setBackground(new java.awt.Color(0, 51, 102));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/update_24.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 51, 102));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cruz.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbIdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbIdDetalle))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbIdVenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbPrecio))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargardatos(DetalleVenta detave) {
        lbIdDetalle.setText(String.valueOf(detave.getIdDetalle()));
        lbIdVenta.setText(String.valueOf(detave.getVenta().getIdVenta()));
        comboProductos.setSelectedIndex(buscarProducto(detave.getProducto().getIdProducto(), detave.getCantidad()));//Agrego los pro al stock
        comboCantidad.setSelectedItem(detave.getCantidad());
        Double pre = buscarPrecioProducto(detave.getProducto().getIdProducto()) * detave.getCantidad();
        lbPrecio.setText("$ "+String.valueOf(pre));
    }

    public void cargarCombo() {
        comboProductos.removeAllItems();
        listaproductos = prodao.listarProductos();
        for (Producto pro : listaproductos) {
            comboProductos.addItem(pro);
        }
    }

    public int buscarProducto(int id, int can) {//Busco el producto seleccionado en la tabla
        int index = 0;
        for (Producto p : listaproductos) {
            index++;
            if (p.getIdProducto() == id) {
                p.setStock(p.getStock() + can);//Le sumo al producto la cantidad del detalle
                prodao.modificarProducto(p);//Modifico el stock del producto
                break;
            }
        }
        return index - 1;
    }

    public void buscarProducto2(int id, int can) {//Busco el producto del combo
        for (Producto p : listaproductos) {
            if (p.getIdProducto() == id) {
                p.setStock(p.getStock() - can);//Le resto al producto la cantidad del detalle
                break;
            }
        }
    }

    public double buscarPrecioProducto(int id) {//Busco el precio del producto seleccionado en la tabla
        double precio = 0;
        for (Producto p : listaproductos) {
            if (p.getIdProducto() == id) {
                precio = p.getPrecioActual();
                break;
            }
        }
        return precio;
    }

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        //COMBOBOX PRODUCTO
        comboCantidad.removeAllItems();
        Producto pro = (Producto) comboProductos.getSelectedItem();
        if (pro != null) {
            int cantidad = pro.getStock();//saco la cantidad de productos que haya
            for (int i = 0; i <= cantidad; i++) {//Cargo el comboCantidad con el stock
                comboCantidad.addItem(i);
            }
        }
    }//GEN-LAST:event_comboProductosActionPerformed

    private void comboCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCantidadActionPerformed
        // COMBOBOX CANTIDAD
        if (comboCantidad.getSelectedItem() != null) {
            int num = (Integer) comboCantidad.getSelectedItem();//TOMAR LA CANTIDAD ELEGIDA
            Producto pro = (Producto) comboProductos.getSelectedItem();
            lbPrecio.setText("$  " + pro.getPrecioActual() * num);//MULTIPLICAR EL PRECIO DEL PRODUCTO PORLA CANTIDAD ELEGIDA
        }
    }//GEN-LAST:event_comboCantidadActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // BOTON ACTUALIZAR
        Venta ve = null;
        Producto pro = null;
        DetalleVenta deta = null;

        if (comboCantidad.getSelectedItem().equals(0)) {
            JOptionPane.showMessageDialog(null, "Seleccione la cantidad de producto");
        } else {

            int pregunta = JOptionPane.showConfirmDialog(//Preguntamos si está seguro de modificar el datalle
                    this, "¿Estas seguro de querer modificar el DetalleVenta?",
                    "Mensaje..!!",
                    JOptionPane.YES_NO_OPTION);
            if (pregunta == JOptionPane.YES_OPTION) {
                ve = new Venta();
                pro = new Producto();
                pro = (Producto) comboProductos.getSelectedItem();
                deta = new DetalleVenta(ve, pro);
                deta.setIdDetalle(Integer.parseInt(lbIdDetalle.getText()));
                deta.getVenta().setIdVenta(Integer.parseInt(lbIdVenta.getText()));
                int can = (int) comboCantidad.getSelectedItem();
                deta.setCantidad(can);
                double pre = pro.getPrecioActual() * can;
                deta.setPrecioTotal(pre);
                detadao.modificarDetalleVenta(deta);
                pro.setStock(pro.getStock() - (Integer) comboCantidad.getSelectedItem());//Seteo el stock  
                prodao.modificarProducto(pro);
                JOptionPane.showMessageDialog(null, "Detalle de Venta Modificado");
                this.dispose();
            }
            if (pregunta == JOptionPane.NO_OPTION) {
                DetalleVenta dv = detadao.buscarDetalleVenta(Integer.parseInt(lbIdDetalle.getText()));
                int id = dv.getProducto().getIdProducto();
                int can = dv.getCantidad();
                pro = new Producto();
                pro = prodao.buscarPorID(id);
                pro.setStock(pro.getStock() - can);
                prodao.modificarProducto(pro);//Dejo el stock como antes
                JOptionPane.showMessageDialog(null, "Modificación cancelada!!");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // BOTON CANCELAR
        DetalleVenta dv = detadao.buscarDetalleVenta(Integer.parseInt(lbIdDetalle.getText()));
        int id = dv.getProducto().getIdProducto();
        int can = dv.getCantidad();
        Producto pro = new Producto();
        pro = prodao.buscarPorID(id);
        pro.setStock(pro.getStock() - can);
        prodao.modificarProducto(pro);//Dejo el stock como antes
        JOptionPane.showMessageDialog(null, "Modificación cancelada!!");
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_Venta dialog = new Modificar_Venta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Integer> comboCantidad;
    private javax.swing.JComboBox<Producto> comboProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIdDetalle;
    private javax.swing.JLabel lbIdVenta;
    private javax.swing.JLabel lbPrecio;
    // End of variables declaration//GEN-END:variables
}
